version: '3'


services:

  trvn-postgres:
    image: postgres:14-alpine
    container_name: 'trvn-postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'trvn'
    labels:
      application: 'trvn-postgres'
    expose:
      - '5432'
    deploy:
      resources:
        limits:
          memory: 512M

  trvn-django:
    build:
      context: ./
    command: "gunicorn trvn_appbackend.wsgi:application --chdir=src --bind 0.0.0.0:8001 --reload --log-file - "
    container_name: 'trvn-django'
    labels:
      application: 'trvn-django'
    volumes:
      - ./:/code
    ports:
      - '8001:8001'
    depends_on:
      - trvn-postgres
    expose:
      - '8001'
    environment: &env
      DEBUG: 'True'
      ALLOWED_HOSTS: '*'
      SECRET_KEY: 'NmzvoVNRBduQ.yN*FmgX.tajt8.yTDY!**BuPGdj'
      DATABASE_URL: 'postgres://postgres:postgres@trvn-postgres:5432/trvn'
      REDIS_URL: 'redis://trvn-redis:6379/1'
    deploy:
      resources:
        limits:
          memory: 512M



  trvn-redis:
    image: redis:latest
    container_name: 'trvn-redis'
    labels:
      application: 'trvn-redis'
    expose:
      - '6379'
    deploy:
      resources:
        limits:
          memory: 512M

