# Generated by Django 3.2.16 on 2022-12-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221215_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
